### ISSUE TITLE
Create React application with Vite

### ISSUE THREAD

**Issue by yurikahirata** [WG-CC/transitiontoolkit-frontend#1]
# Problem
Setup React and TypeScript with Vite using the following documentation:
https://vitejs.dev/guide/

Install TailwindCSS using the following documentation:
https://tailwindcss.com/docs/guides/vite

# Success
Running a command that spins up React.

### Requirements

- [x] Create new branch from dev (name/issue Ex: yurika/setup-react)
- [x] Install React and TypeScript with Vite
- [x] Install Tailwind CSS
- [x] Remove unnecessary code (extra css files, logos, etc)
- [x] Update frontend repository README to include installation guide (setup, commands)

**Comment by NabbeunNabi** [comment]
Should this spin up with a yarn command since we decided to use yarn? And if so is that a separate issue to set up yarn or would that be part of this?

**Comment by hccleveland** [comment]
Resolved with  PR https://github.com/WG-CC/transitiontoolkit-frontend/pull/7
